# Generated by Django 5.2 on 2025-04-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evvehicle',
            name='production_price',
            field=models.FloatField(default=1000, verbose_name='Стоимость производства'),
        ),
        migrations.AddField(
            model_name='hevvehicle',
            name='production_price',
            field=models.FloatField(default=1000, verbose_name='Стоимость производства'),
        ),
        migrations.AddField(
            model_name='icevehicle',
            name='production_price',
            field=models.FloatField(default=1000, verbose_name='Стоимость производства'),
        ),
    ]
