# Generated by Django 5.2 on 2025-04-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_evvehicle_production_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hevvehicle',
            name='transmission_ratio',
        ),
        migrations.RemoveField(
            model_name='icevehicle',
            name='transmission_ratio',
        ),
    ]
