# Generated by Django 5.2 on 2025-04-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_rename_name_evvehicle_model_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evvehicle',
            name='drag_coefficient',
        ),
        migrations.RemoveField(
            model_name='evvehicle',
            name='rolling_coefficient',
        ),
        migrations.RemoveField(
            model_name='hevvehicle',
            name='drag_coefficient',
        ),
        migrations.RemoveField(
            model_name='hevvehicle',
            name='rolling_coefficient',
        ),
        migrations.RemoveField(
            model_name='icevehicle',
            name='drag_coefficient',
        ),
        migrations.RemoveField(
            model_name='icevehicle',
            name='rolling_coefficient',
        ),
        migrations.RemoveField(
            model_name='phevvehicle',
            name='drag_coefficient',
        ),
        migrations.RemoveField(
            model_name='phevvehicle',
            name='rolling_coefficient',
        ),
    ]
