# Generated by Django 5.2 on 2025-04-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_remove_evvehicle_drag_coefficient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phevvehicle',
            options={},
        ),
        migrations.RemoveField(
            model_name='phevvehicle',
            name='battery_capacity_kwh',
        ),
        migrations.RemoveField(
            model_name='phevvehicle',
            name='battery_depletion_threshold',
        ),
        migrations.RemoveField(
            model_name='phevvehicle',
            name='charging_power_kw',
        ),
        migrations.RemoveField(
            model_name='phevvehicle',
            name='electric_range_km',
        ),
        migrations.RemoveField(
            model_name='phevvehicle',
            name='energy_consumption_kwhp100km',
        ),
        migrations.RemoveField(
            model_name='phevvehicle',
            name='engine_efficiency',
        ),
        migrations.RemoveField(
            model_name='phevvehicle',
            name='fuel_consumption_lp100km',
        ),
        migrations.RemoveField(
            model_name='phevvehicle',
            name='ice_range_km',
        ),
        migrations.RemoveField(
            model_name='phevvehicle',
            name='regen_braking_efficiency',
        ),
        migrations.AddField(
            model_name='phevvehicle',
            name='battery_only_range_km',
            field=models.FloatField(default=0.0, help_text='По данным производителя (WLTP или NEDC)', verbose_name='Запас хода только на батарее (км)'),
        ),
        migrations.AddField(
            model_name='phevvehicle',
            name='car_price_eur',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена автомобиля (EUR)'),
        ),
        migrations.AddField(
            model_name='phevvehicle',
            name='kwh_100_km_battery_only',
            field=models.FloatField(default=0.0, help_text='В режиме только на батарее', verbose_name='Потребление энергии (кВт·ч/100 км)'),
        ),
        migrations.AddField(
            model_name='phevvehicle',
            name='mpg_gas_only',
            field=models.FloatField(default=0.0, help_text='Miles per gallon в режиме только ДВС', verbose_name='MPG при работе только на ДВС'),
        ),
    ]
