# Generated by Django 5.2 on 2025-04-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_phevvehicle_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phevvehicle',
            name='car_price_eur',
        ),
    ]
